### ISSUE TITLE
在win7上，fecs output虽然有，但不指出哪里格式错误~

### ISSUE THREAD

**Issue by TJ666** [MarxJiao/VScode-fecs#13]
在win7上，fecs output虽然有，但不指出哪里格式错误,貌似工具缺少包，报错了？

比方我在句尾加空格，fecs output 
module.js:471
    throw err;
    ^

Error: Cannot find module 'msee'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\fecs\lib\cli.js:9:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by MarxJiao** [comment]
不使用插件，直接在命令行执行fecs报错吗？如果也报错，可以到fecs问问。
